// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feeds_users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollowUser = `-- name: CreateFeedFollowUser :one
INSERT INTO feeds_users (id, created_at, updated_at, user_id, feed_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateFeedFollowUserParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) CreateFeedFollowUser(ctx context.Context, arg CreateFeedFollowUserParams) (FeedsUser, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollowUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FeedsUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const deleteFeedFollowUser = `-- name: DeleteFeedFollowUser :exec
DELETE FROM feeds_users WHERE user_id = $1 AND feed_id = $2
`

type DeleteFeedFollowUserParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DeleteFeedFollowUser(ctx context.Context, arg DeleteFeedFollowUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowUser, arg.UserID, arg.FeedID)
	return err
}

const getFeedFollowUser = `-- name: GetFeedFollowUser :many
SELECT id, created_at, updated_at, user_id, feed_id FROM feeds_users WHERE user_id = $1
`

func (q *Queries) GetFeedFollowUser(ctx context.Context, userID uuid.UUID) ([]FeedsUser, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedsUser
	for rows.Next() {
		var i FeedsUser
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
